<a href="https://colab.research.google.com/github/ksy202206153/Aipython/blob/main/250509.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:

import numpy as np



In [23]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [24]:
b = np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


In [25]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [26]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[arr%2==0])

[ 2  4  6  8 10]


In [29]:
x = np.array([2,4,6])
y = np.array([10,20,30])
result = x*y
print(result)

[ 20  80 180]


In [30]:
print(result[result>20])

[ 80 180]


In [21]:
import pandas as pd

In [32]:
s = pd.Series([10, 20, 30, 40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64


In [37]:
data = {
    '이름': ['홍길동', '김철수', '이영희'],
    '나이': [25, 30, 27],
    '성별': ['남', '남', '여']
}

df = pd.DataFrame(data)
print(df)

    이름  나이 성별
0  홍길동  25  남
1  김철수  30  남
2  이영희  27  여


In [38]:
df

이름  나이 성별
0  홍길동  25  남
1  김철수  30  남
2  이영희  27  여

In [39]:
df.to_csv('output_students.csv', index=False)

In [41]:
df = pd.read_csv('output_students.csv')
print(df.head())  # 처음 5행만 출력

    이름  나이 성별
0  홍길동  25  남
1  김철수  30  남
2  이영희  27  여


In [50]:
df = pd.read_csv('train_and_test2.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 28 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Passengerid  1309 non-null   int64  
 1   Age          1309 non-null   float64
 2   Fare         1309 non-null   float64
 3   Sex          1309 non-null   int64  
 4   sibsp        1309 non-null   int64  
 5   zero         1309 non-null   int64  
 6   zero.1       1309 non-null   int64  
 7   zero.2       1309 non-null   int64  
 8   zero.3       1309 non-null   int64  
 9   zero.4       1309 non-null   int64  
 10  zero.5       1309 non-null   int64  
 11  zero.6       1309 non-null   int64  
 12  Parch        1309 non-null   int64  
 13  zero.7       1309 non-null   int64  
 14  zero.8       1309 non-null   int64  
 15  zero.9       1309 non-null   int64  
 16  zero.10      1309 non-null   int64  
 17  zero.11      1309 non-null   int64  
 18  zero.12      1309 non-null   int64  
 19  zero.1

In [49]:
df.describe()

Passengerid          Age         Fare          Sex        sibsp  \
count  1309.000000  1309.000000  1309.000000  1309.000000  1309.000000   
mean    655.000000    29.503186    33.281086     0.355997     0.498854   
std     378.020061    12.905241    51.741500     0.478997     1.041658   
min       1.000000     0.170000     0.000000     0.000000     0.000000   
25%     328.000000    22.000000     7.895800     0.000000     0.000000   
50%     655.000000    28.000000    14.454200     0.000000     0.000000   
75%     982.000000    35.000000    31.275000     1.000000     1.000000   
max    1309.000000    80.000000   512.329200     1.000000     8.000000   

         zero  zero.1  zero.2  zero.3  zero.4  ...  zero.12  zero.13  zero.14  \
count  1309.0  1309.0  1309.0  1309.0  1309.0  ...   1309.0   1309.0   1309.0   
mean      0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   
std       0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   
min       0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   
25%       0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   
50%       0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   
75%       0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   
max       0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   

            Pclass  zero.15  zero.16     Embarked  zero.17  zero.18  \
count  1309.000000   1309.0   1309.0  1307.000000   1309.0   1309.0   
mean      2.294882      0.0      0.0     1.492731      0.0      0.0   
std       0.837836      0.0      0.0     0.814626      0.0      0.0   
min       1.000000      0.0      0.0     0.000000      0.0      0.0   
25%       2.000000      0.0      0.0     1.000000      0.0      0.0   
50%       3.000000      0.0      0.0     2.000000      0.0      0.0   
75%       3.000000      0.0      0.0     2.000000      0.0      0.0   
max       3.000000      0.0      0.0     2.000000      0.0      0.0   

          2urvived  
count  1309.000000  
mean      0.261268  
std       0.439494  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       1.000000  
max       1.000000  

[8 rows x 28 columns]

In [52]:
df['Age']

0       22.0
1       38.0
2       26.0
3       35.0
4       35.0
        ... 
1304    28.0
1305    39.0
1306    38.5
1307    28.0
1308    28.0
Name: Age, Length: 1309, dtype: float64

In [57]:
df[df['Age']<25]

Passengerid   Age     Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
0               1  22.0   7.2500    0      1     0       0       0       0   
7               8   2.0  21.0750    0      3     0       0       0       0   
9              10  14.0  30.0708    1      1     0       0       0       0   
10             11   4.0  16.7000    1      1     0       0       0       0   
12             13  20.0   8.0500    0      0     0       0       0       0   
...           ...   ...      ...  ...    ...   ...     ...     ...     ...   
1293         1294  22.0  59.4000    1      0     0       0       0       0   
1294         1295  17.0  47.1000    0      0     0       0       0       0   
1296         1297  20.0  13.8625    0      0     0       0       0       0   
1297         1298  23.0  10.5000    0      1     0       0       0       0   
1300         1301   3.0  13.7750    1      1     0       0       0       0   

      zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  \
0          0  ...        0        0        0       3        0        0   
7          0  ...        0        0        0       3        0        0   
9          0  ...        0        0        0       2        0        0   
10         0  ...        0        0        0       3        0        0   
12         0  ...        0        0        0       3        0        0   
...      ...  ...      ...      ...      ...     ...      ...      ...   
1293       0  ...        0        0        0       1        0        0   
1294       0  ...        0        0        0       1        0        0   
1296       0  ...        0        0        0       2        0        0   
1297       0  ...        0        0        0       2        0        0   
1300       0  ...        0        0        0       3        0        0   

      Embarked  zero.17  zero.18  2urvived  
0          2.0        0        0         0  
7          2.0        0        0         0  
9          0.0        0        0         1  
10         2.0        0        0         1  
12         2.0        0        0         0  
...        ...      ...      ...       ...  
1293       0.0        0        0         0  
1294       2.0        0        0         0  
1296       0.0        0        0         0  
1297       2.0        0        0         0  
1300       2.0        0        0         0  

[409 rows x 28 columns]

In [58]:
df.dropna()

Passengerid   Age      Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
0               1  22.0    7.2500    0      1     0       0       0       0   
1               2  38.0   71.2833    1      1     0       0       0       0   
2               3  26.0    7.9250    1      0     0       0       0       0   
3               4  35.0   53.1000    1      1     0       0       0       0   
4               5  35.0    8.0500    0      0     0       0       0       0   
...           ...   ...       ...  ...    ...   ...     ...     ...     ...   
1304         1305  28.0    8.0500    0      0     0       0       0       0   
1305         1306  39.0  108.9000    1      0     0       0       0       0   
1306         1307  38.5    7.2500    0      0     0       0       0       0   
1307         1308  28.0    8.0500    0      0     0       0       0       0   
1308         1309  28.0   22.3583    0      1     0       0       0       0   

      zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  \
0          0  ...        0        0        0       3        0        0   
1          0  ...        0        0        0       1        0        0   
2          0  ...        0        0        0       3        0        0   
3          0  ...        0        0        0       1        0        0   
4          0  ...        0        0        0       3        0        0   
...      ...  ...      ...      ...      ...     ...      ...      ...   
1304       0  ...        0        0        0       3        0        0   
1305       0  ...        0        0        0       1        0        0   
1306       0  ...        0        0        0       3        0        0   
1307       0  ...        0        0        0       3        0        0   
1308       0  ...        0        0        0       3        0        0   

      Embarked  zero.17  zero.18  2urvived  
0          2.0        0        0         0  
1          0.0        0        0         1  
2          2.0        0        0         1  
3          2.0        0        0         1  
4          2.0        0        0         0  
...        ...      ...      ...       ...  
1304       2.0        0        0         0  
1305       0.0        0        0         0  
1306       2.0        0        0         0  
1307       2.0        0        0         0  
1308       0.0        0        0         0  

[1307 rows x 28 columns]

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 28 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Passengerid  1309 non-null   int64  
 1   Age          1309 non-null   float64
 2   Fare         1309 non-null   float64
 3   Sex          1309 non-null   int64  
 4   sibsp        1309 non-null   int64  
 5   zero         1309 non-null   int64  
 6   zero.1       1309 non-null   int64  
 7   zero.2       1309 non-null   int64  
 8   zero.3       1309 non-null   int64  
 9   zero.4       1309 non-null   int64  
 10  zero.5       1309 non-null   int64  
 11  zero.6       1309 non-null   int64  
 12  Parch        1309 non-null   int64  
 13  zero.7       1309 non-null   int64  
 14  zero.8       1309 non-null   int64  
 15  zero.9       1309 non-null   int64  
 16  zero.10      1309 non-null   int64  
 17  zero.11      1309 non-null   int64  
 18  zero.12      1309 non-null   int64  
 19  zero.1

In [60]:
df3 = df.dropna()
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1307 entries, 0 to 1308
Data columns (total 28 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Passengerid  1307 non-null   int64  
 1   Age          1307 non-null   float64
 2   Fare         1307 non-null   float64
 3   Sex          1307 non-null   int64  
 4   sibsp        1307 non-null   int64  
 5   zero         1307 non-null   int64  
 6   zero.1       1307 non-null   int64  
 7   zero.2       1307 non-null   int64  
 8   zero.3       1307 non-null   int64  
 9   zero.4       1307 non-null   int64  
 10  zero.5       1307 non-null   int64  
 11  zero.6       1307 non-null   int64  
 12  Parch        1307 non-null   int64  
 13  zero.7       1307 non-null   int64  
 14  zero.8       1307 non-null   int64  
 15  zero.9       1307 non-null   int64  
 16  zero.10      1307 non-null   int64  
 17  zero.11      1307 non-null   int64  
 18  zero.12      1307 non-null   int64  
 19  zero.13    

In [62]:
result = df.groupby('Sex')['Age'].mean()
print(result)

Sex
0    30.017888
1    28.479720
Name: Age, dtype: float64
